name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      cmd:
        description: 'command'
jobs:
  which_cmd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: mail.py
        run: ./mail.py
