name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      cmd:
        description: 'command'
jobs:
  which_cmd:
    runs-on: ubuntu-latest
    steps:
      - run: |
          which ${{ github.event.inputs.cmd }}
