name: One-hosted-test
on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Testing issue number'
        required: true
env:
  issue_num: "${{ github.event.inputs.number || 37 }}"


jobs:
  labeled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: echo1
        run: |
          test.rb

