name: Labeling issue
on:
  issues:
    types:
      - labeled

jobs:
  mail-details:
    runs-on: ubuntu-latest
    steps:
      - name: Issue number
        run: "echo ${{ github.event.issue.number }}"
      - name: Issue title
        run: "echo ${{ github.event.issue.title }}"
      - name: save mail body
        id: deploy
        run: |
          echo ::set-output name=mail_body::"abc%0Abbb%0Accc"
          echo ::set-output name=recepient::"jorel@opennebula.io"

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.opennebula.org
          server_port: 587
          username: infra@opennebula.org
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Github Actions
          to: ${{ steps.deploy.outputs.recepient }}
          from: One Hosted
          body: ${{ steps.deploy.outputs.mail_body }}
          ignore_cert: true

