name: Labeling issue
on:
  workflow_dispatch:
    inputs:
      test_issue_number:
        description: 'Testing issue number'
        required: true

jobs:
  labeled:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Standard
        run: |
          gem install rspec faraday

      - name: Standard
        run: |
          rspec test.spec

