on:
  workflow_dispatch:
    inputs:
      one_hosted_name:
        description: 'One-hosted name'
        required: true
        default: 'demo'
      options:
        description: 'options.yml location'
        required: true
        default: 'options.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
			- run: |
					echo "name: ${{ github.event.inputs.one_hosted_name }}"
					echo "options: ${{ github.event.inputs.options }}"
			- uses: actions/checkout@v1
			- uses: ./action-deploy
				with:
					NAME: "${{ github.event.inputs.one_hosted_name }}"
