name: One-hosted-test
on:
  schedule:
    - cron:  '10 14 * * 1,4'

  workflow_dispatch:
    inputs:
      number:
        description: 'Testing issue number'
        required: true
env:
  issue_num: "${{ github.event.inputs.number || 37 }}"


jobs:
  labeled:
    runs-on: ubuntu-latest
    steps:
      - name: Standard
        run: |
          echo "HERE: ${{ env.issue_num }}"

