name: One-hosted-test
on:
  schedule:
    - cron:  '13 12 * * 1,4'

  workflow_dispatch:
    inputs:
      number:
        description: 'Testing issue number'
        required: true
env:
  issue_num: "${{ github.event.inputs.number || 37 }}"


jobs:
  labeled:
    runs-on: ubuntu-latest
    steps:
      - name: echo1
        run: |
          echo "HERE 1"

      - name: err_false
        run: |
          false

      - name: echo2
        run: |
          echo "HERE 2"
