name: Labeling issue
on:
  issues:
    types:
      - labeled

jobs:
  labeled:
    runs-on: ubuntu-latest
    steps:
      - name: Add abc label
        run: |
          curl  -H "Accept: application/vnd.github.v3+json" -X POST -u xorel:${{ secrets.PAT }}   https://api.github.com/repos/xorel/hello-github-actions/issues/4/labels -d '["abc"]'

