name: Labeling issue
on:
  issues:
    types:
      - labeled

jobs:
  echo-details:
    runs-on: ubuntu-latest
    steps:
      - name: Issue number
        run: "echo ${{ github.event.issue.number }}"
      - name: Issue title
        run: "echo ${{ github.event.issue.title }}"
      - name: Issue body
        run: "echo ${{ github.event.issue.body }}"

      - name: echo
        shell: bash
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: 'echo $MY_SECRET'

      - name: echo | wc
        shell: bash
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: 'echo "$MY_SECRET" | wc -l'

      - name: echo | base64
        shell: bash
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: 'echo "$MY_SECRET" | base64'
