name: Test
on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Testing issue number'
        required: true
env:
  issue_num: "${{ github.event.inputs.number || 37 }}"


jobs:
  labeled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true


      - name: echo1
        run: "ruby test.rb"

