name: Labeling issue
on:
  issues:
    types:
      - labeled

jobs:
  echo-details:
    if: github.event.label.name == 'action-deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Issue number
        run: "echo ${{ github.event.issue.number }}"
      - name: Issue title
        run: "echo ${{ github.event.issue.title }}"
      - name: Issue body
        run: "echo ${{ github.event.issue.body }}"
